# Documentation: https://roots.io/trellis/docs/ssh-keys/
admin_user: admin

# Also define 'vault_users' (`group_vars/staging/vault.yml`, `group_vars/production/vault.yml`)
users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
    keys:
             - http://alt-d.co.uk/keys.txt
   
  - name: "{{ admin_user }}"
    groups:
      - sudo
    keys:
         - http://alt-d.co.uk/keys.txt
web_user: alt-d
web_group: www-data
web_sudoers:
  - "/usr/sbin/service php7.3-fpm *"
